name: ClinicFlow Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# CRITICAL: This allows GitHub to request the identity token from AWS
permissions:
  id-token: write
  contents: read

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::541495491866:role/ClinicFlow-GitHub-Actions-Role
          aws-region: us-east-1

      - name: Run Checkov Scan (Hard Enforcement)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/clinicflow-vault
          framework: terraform
          # CHANGED: We now physically break the build on a security violation
          soft_fail: false